### ISSUE TITLE
Bump to newer dependencies?

### ISSUE THREAD

**Issue by utkarsh2102** [jruby/rake-ant#2]
Hello,

https://github.com/jruby/rake-ant/blob/317930bfd76d8330a94b3f8aacb59e14ba92c669/rake-ant.gemspec#L22-L23

These versions are a bit too old. Do you think we can move to bundler 2.x and rake 13.x?
Besides, Ruby 3.0 is out. While at it, can we make sure it is ready for that as well?

**Comment by headius** [comment]
I see no reason not to update development depedencies. As for Ruby 3.0, this gem is specific to JRuby (uses our Java integration layer) so that won't be relevant until JRuby supports 3.0 features (some time in 2021).

**Comment by utkarsh2102** [comment]
Aah, that makes sense. Do you want me to open a PR for bumping the dependendies? Could you maybe do a patch release post that?

**Comment by headius** [comment]
@utkarsh2102 Sure, post a PR! We can spin a release but this change won't have any visible impact since these are *development dependencies* and are only used during local development of the rake-ant code.

**Comment by utkarsh2102** [comment]
> We can spin a release but this change won't have any visible impact since these are development dependencies and are only used during local development of the rake-ant code.

That's right. But I ask for new release because we're updating the version of `jruby` in Debian and for that we need to package `rake-ant` to build. So whilst building `rake-ant` in Debian, it'd be great if we have the newer versions of rake and bundler! 😄

**Comment by utkarsh2102** [comment]
> Sure, post a PR! 

Done via #3! 🎉

**Comment by headius** [comment]
@utkarsh2102 Thank you!
