### ISSUE TITLE
Drop git from gemspec?

### ISSUE THREAD

**Issue by utkarsh2102** [jruby/rake-ant#4]
Hello,

https://github.com/jruby/rake-ant/blob/317930bfd76d8330a94b3f8aacb59e14ba92c669/rake-ant.gemspec#L17-L19

Using git in gemspec is somewhat problematic and it's best if avoided.
Here's the more verbose rationale: https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#gemspec-git-rationale

If you agree to drop `git` from gemspec and use `Dir` or `Dir.glob`, I'd be happy to raise a PR! Let me know what you think?

**Comment by headius** [comment]
I think for this library it would be fine to use `Dir` instead of the call to `git`. Go for it!
